name: calculator_plus
description: A Demo Project for Flutter + Rust Implementation. Flutter Version - 3.16.8
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  ffi: ^2.1.0
  flutter_rust_bridge: ^1.82.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  ffigen: 8.0.2
  build_runner: ^2.4.8
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1

flutter:
  uses-material-design: true
